### ISSUE TITLE
Fuzzy search?

### ISSUE THREAD

**Issue by milesgranger** [SeekStorm/SeekStorm#14]
Hi, I'm just trialing this to maybe move from Meilisearch. Indexing ~5M documents it's noticeably faster both when adding documents and searching; also smaller indexing size on disk which is great.

However, I maybe have setup my index wrong or am missing something obvious regarding fuzzy search [1]. If I misspell a word by a single letter I get zero results which also happens on the demo: https://deephn.org/?q=revieww&fq=1 (misspell review -> 'revieww')

I briefly went over the seekstorm_server and found ['suggestions'](https://github.com/search?q=repo%3ASeekStorm%2FSeekStorm%20suggestions&type=code) only referenced a couple times as the demo also automatically replaces the wrongly entered 'revieww' with 'review'; so _appears_ that's happening outside of seekstorm but it wasn't immediately clear.

Again, apologies if I've overlooked something obvious here. :) 

[1] Fuzzy search is mentioned in the README as having been ported (https://github.com/SeekStorm/SeekStorm/tree/main?tab=readme-ov-file#roadmap). Also searched the docs site without finding anything regarding this.

**Comment by wolfgarbe** [comment]
The demo and the SaaS are still based on the SeekStorm C# codebase (that contains spelling correction based on [SymSpell](https://github.com/wolfgarbe/SymSpell), auto-completion, and instant search). The SeekStorm Rust port is not yet feature-complete and doesn't include auto-completion and instant search yet. But that's on the [roadmap](https://github.com/SeekStorm/SeekStorm?tab=readme-ov-file#roadmap).

In the meantime, you could use one of the SymSpell Rust ports, e.g. https://github.com/reneklacan/symspell to implement query rewriting.

> Fuzzy search is mentioned in the README as having been ported 

That is a misunderstanding. Only those items in the roadmap that got a green checkmark have already been ported. The other items are still waiting to be ported.

**Comment by milesgranger** [comment]
Ah, I see now. Thanks for the clarification! 🙌
