### ISSUE TITLE
Field limits conflicting documentation

### ISSUE THREAD

**Issue by tv42** [SeekStorm/SeekStorm#18]
https://github.com/SeekStorm/SeekStorm/blob/c1d351296f9471264993cf9cab2fd6dfb770d120/ARCHITECTURE.md#L65-L68

but https://seekstorm.com/docs/#create-index says

> The number of facet fields (type stringFacet, integerFacet, floatFacet, dateFacet) is limited to 10 per index. The number of index fields (types: title, url, text, index) together is limited to an additional 16. Of this, the number of type title, url, text is each limited to 1. The number of fields of NoIndex type is unlimited. NoIndex fields can be of any JSON type (number, string, boolean). They are not indexed and not searchable. But with the property store=true they are stored and can be retrieved as a payload in the search results. The string length of any field name is limited to 100 characters.

Please clarify. Is this unlimited in open source and limited in SaaS, or is one of these wrong? Is there open source API documentation independent of the SaaS limitations?

**Comment by wolfgarbe** [comment]
> Please clarify. Is this unlimited in open source and limited in SaaS, or is one of these wrong?

We have two different code bases:
1. SeekStorm C#, used in SeekStorm search-as-a-service, REST API documentation https://seekstorm.com/docs/ , limited fields
2. SeekStorm Rust, Open-Source at Github repository, REST API documentation https://seekstorm.apidocumentation.com/reference , library documentation https://docs.rs/seekstorm, unlimited fields

In 2023 we started to partially port, and partially rewrite from C# to Rust. We made changes to the architecture, data structures, and some algorithms to improve performance, make everything more universal and remove the limitations from the old implementation. Feature set and API are similar, but not identical. Ultimately we will use the new Rust implementation also for the search-as-a-service

> Is there open source API documentation independent of the SaaS limitations?

Yes, both are linked at the top of the SeekStorm Github repository:
- SeekStorm Rust Library documentation: https://docs.rs/seekstorm
- SeekStorm Rust Server REST API documentation: https://seekstorm.apidocumentation.com/
