### ISSUE TITLE
Crashing with Index out of bounds or range out of range for slice of length

### ISSUE THREAD

**Issue by westadaptive** [SeekStorm/SeekStorm#5]
This is a very cool product! 

I setup a local test and when I do searches I randomly get index out of bounds error such as this:

thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-main 3/src/seekstorm/intersection.rs:936:38:
index out of bounds: the len is 521 but the index is 521
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: seekstorm::intersection::intersection_docid::{{closure}}.4929
   4: seekstorm::intersection::intersection_blockid::{{closure}}.4926
   5: <alloc::sync::Arc<tokio::sync::rwlock::RwLock<seekstorm::index::Index>> as seekstorm::search::Search>::search::{{closure}}.4905
   6: seekstorm_server::api_endpoints::query_index_api::{{closure}}.4893
   7: seekstorm_server::http_server::http_request_handler::{{closure}}.4853
   8: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
   9: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  10: tokio::runtime::task::core::Core<T,S>::poll
  11: tokio::runtime::task::raw::poll
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  13: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: abort      RUST_BACKTRACE=1 ./seekstorm_server local_ip="0.0.0.0" local_port=8020

or range end index out of range errors. 

thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-main 3/src/seekstorm/utils.rs:103:28:
range end index 5970246 out of range for slice of length 2604
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail
   3: seekstorm::intersection::intersection_docid::{{closure}}.4929
   4: seekstorm::intersection::intersection_blockid::{{closure}}.4926
   5: <alloc::sync::Arc<tokio::sync::rwlock::RwLock<seekstorm::index::Index>> as seekstorm::search::Search>::search::{{closure}}.4905
   6: seekstorm_server::api_endpoints::query_index_api::{{closure}}.4893
   7: seekstorm_server::http_server::http_request_handler::{{closure}}.4853
   8: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
   9: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  10: tokio::runtime::task::core::Core<T,S>::poll
  11: tokio::runtime::task::raw::poll
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  13: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: abort      RUST_BACKTRACE=1 ./seekstorm_server local_ip="0.0.0.0" local_port=8020

Format of my data is like this: 

{"address": "123 N 4TH ST, DUPO, IL", "postcode": "61234"}
{"address": "456 N 2ND ST, DUPO, IL", "postcode": "12345"}
{"address": "789 N 5TH ST, DUPO, IL", "postcode": "12345"}

I am new to Rust so I am having a bit of trouble figuring out the errors.  Thank you for your help I really appreciate it.

**Comment by wolfgarbe** [comment]
Thank you very much for the report. 
It seems you were using the seekstorm server. Please help me to replicate the problem. 
What parameters and schema did you use for the create_index API? What data did you index? What queries/parameters did you send to the server via the query_index API?
Having all the API requests in cURL/JSON format sent to the server before the exception would help to replicate and fix.

Thank you

**Comment by westadaptive** [comment]
Thank you for the quick reply. 
Here are the steps I took. 

1) I edited the ingest match in server.rs to change the schema to address and postcode.: 
```
 "ingest" =>
                    {

                        let apikey_quota_object=ApikeyQuotaObject {..Default::default()};

                        let mut apikey_list_mut = apikey_list_clone.write().await;
                        let apikey_object=create_apikey_api(
                            &index_path,
                            apikey_quota_object,
                            &demo_api_key,
                            &mut apikey_list_mut,
                        );

                        let wikipedia_schema_json = r#"
                        [{"field":"address","field_type":"Text","stored":true,"indexed":true,"boost":10.0},
                        {"field":"postcode","field_type":"Text","stored":true,"indexed":true}]"#;
                        let schema = serde_json::from_str(wikipedia_schema_json).unwrap();

                        let index_id = create_index_api(
                            &index_path,
                            "wikipedia".to_string(),
                            schema,
                            SimilarityType::Bm25fProximity,
                            TokenizerType::UnicodeAlphanumeric,
                            apikey_object,
                        );

                        let apikey_hash = calculate_hash(&demo_api_key) as u128;
                        let apikey_object=apikey_list_mut.get(&apikey_hash).unwrap();
                        let index_arc=apikey_object.index_list.get(&index_id).unwrap();
                        let index_arc_clone=index_arc.clone();

                        drop(apikey_list_mut);

                        let data_path=if parameter.len()>1 {parameter[1]} else {"addresses.json"};
                        ingest_ndjson(index_arc_clone,data_path).await;

                        println!("Set the 'individual API key' in test_api.rest to '{}' when testing the REST API endpoints",demo_api_key_base64);
                    },
```

2) Then I ran `cargo build --release `

3) Next I ran` ./seekstorm_server local_ip="0.0.0.0" local_port=8020`

4) Next I ran "ingest" , the import was successful. 

5) as soon as I start typing in "123 Main St" It crashes at "123 Main S"  - when crashes it would give me this error: 
```

thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-main 3/src/seekstorm/utils.rs:103:28:
range end index 1971674 out of range for slice of length 33632
```


6) this query "1234 maple ave chicago" would give me this error: 

```
thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-main 3/src/seekstorm/intersection.rs:936:38:
index out of bounds: the len is 183 but the index is 183
```


Thank you very much for your help. The data is US addresses, I have emailed the link with the full dataset and my SeekStorm directory with the index data as well.

**Comment by wolfgarbe** [comment]
Thank you for all the information.

The UI is hard-wired for the Wikipedia demo schema (which you have changed). 
To display fields from a modified schema you need to edit [/src/seekstorm_server/web/js/master.js](../blob/main/src/seekstorm_server/web/js/master.js) (and possibly   [/src/seekstorm_server/web/index.html](../blob/main/src/seekstorm_server/web/index.html)  ) before building as well.
I should have mentioned this in the readme or made the UI universal for any schema.

line 92
```
$.ajax({
    url: QUERY_URL,
    data: JSON.stringify({ 
       query: query,
       offset: (page - 1) * 10,
       length: 10,
       realtime: true,
       highlights: [
        { field: "address", fragment_number: 0, fragment_size: 1000, highlight_markup: true},
        { field: "postcode", fragment_number: 2, fragment_size: 160, highlight_markup: true},
        { field: "postcode", name: "body2", fragment_number: 0, fragment_size: 4000, highlight_markup: true}]
    }),
```

line 131

```
<div class="col-xs-${iUrl ? 10 : 12}">
		<h1>
          <img height="14px" src="favicon-16x16.png"></img>
			<a href="${element.url}">${element.address}</a>
		</h1>
		<p class="kwic">${element.postcode}</p>
		<p class="directLink"><a href="${element.url}">${element.url}</a></p>
	</div>
```

line 143

```
      newEntry.hover(() => {
        moveSplitter(newEntry[0].getBoundingClientRect().y);
        prevUrl.html(element.url);
        prevTitle.html(element.address);
		    prevText.html(element.body2.replace(new RegExp("\r", "gi"), "<br>"));
      });
```

This fixes the UI problem. 
<img width="854" alt="image" src="https://github.com/user-attachments/assets/5b4295a1-9f9b-48ec-baa6-3dada462c966">


I will continue to investigate the crash

**Comment by westadaptive** [comment]
Thank you for the UI tips, I edited and it looks great now. Looking forward for the crash fix.

**Comment by wolfgarbe** [comment]
Before the next public release I need to do some more testing.
But as a quick fix you can apply the following changes:

Change in [src/seekstorm/intersection.rs](https://github.com/SeekStorm/SeekStorm/blob/main/src/seekstorm/intersection.rs#234) line 234

from
```rust
query_list_item_mut.p_run_sum =
    if query_list_item_mut.compression_type == CompressionType::Rle {
        read_u16(
            query_list_item_mut.byte_array,
            query_list_item_mut.compressed_doc_id_range + 4,
        )
        .into()
    } else {
        0
    };
```

to

```rust
query_list_item_mut.p_run_sum =
    if query_list_item_mut.compression_type == CompressionType::Rle {

  query_list_item_mut.p_run_count = read_u16(
            query_list_item_mut.byte_array,
            query_list_item_mut.compressed_doc_id_range,
        ) as i32;

        read_u16(
            query_list_item_mut.byte_array,
            query_list_item_mut.compressed_doc_id_range + 4,
        )
        .into()
    } else {
        0
    };
```

and change in [src/seekstorm/intersection.rs](https://github.com/SeekStorm/SeekStorm/blob/main/src/seekstorm/intersection.rs#1347) line 1347

from
```rust
continue 'start;
```

to
```rust
continue 'restart;
```

**Comment by westadaptive** [comment]
Thank you!!! It works perfectly now.

**Comment by westadaptive** [comment]
Update: I get index out of bounds for some queries. Will do further testing and report back with the details. Thanks.

**Comment by wolfgarbe** [comment]
Commit ade2041 fixed the issue

**Comment by wolfgarbe** [comment]
> Update: I get index out of bounds for some queries. Will do further testing and report back with the details. Thanks.

Yes, there is an exception when searching a term with 65.536 postings per block, e.g. when searching 'oh' in your test index. 
But that is an unrelated problem I will fix in an separate commit.
Please let me know your findings.

**Comment by wolfgarbe** [comment]
The following change in [src/seekstorm/index_posting.rs](https://github.com/SeekStorm/SeekStorm/blob/ade20417333a2a26da5c5940ab7d362cdae985c7/src/seekstorm/index_posting.rs#L146) line 146

from
```rust
let mut posting_pointer_size = if value.size_compressed_positions_key < 32_768 {
    value.pointer_pivot_p_docid = value.posting_count as u16 + 1;
    2u8
} else {
    3u8
};
```

to
```rust
let mut posting_pointer_size = if value.size_compressed_positions_key < 32_768 && value.posting_count<65_535 {
    value.pointer_pivot_p_docid = value.posting_count as u16 + 1;
    2u8
} else {
    3u8
};
```

should fix the out of bounds. Unfortunately this is a breaking change that requires reindexing!

Please let me know if the fix works for you. Thanks.

**Comment by westadaptive** [comment]
Thank you for the updated code, it has fixed the issue for some queries. I still have two diffrent errors I encountered for the following queries. I did delete and reindex the data before running the queries. 

Query 1: 123 Main St

Query  CURL: `curl --location 'http://127.0.0.1:8020/api/v1/index/0/query?query=123%20Main%20St&offset=0&length=10' \
--header 'Content-Type: application/json' \
--header 'apikey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='`

Query 1 Error: `andy@Andys-iMac release % RUST_BACKTRACE=full ./seekstorm_server local_ip="0.0.0.0" local_port=8020
SeekStorm server v0.6.1 starting ...
Hit CTRL-C or enter 'quit' to shutdown server
opening index ...
index.bin name wikipedia id 0 version 3.2 3.2 level 1999 fields 2 2 facets 0 docs 130,987,896 deleted 0 segments 2048 time 0 s
Listening on: 0.0.0.0 8020 index dir /Users/andy/Downloads/SeekStorm-0.6.1/target/release/seekstorm_index master key XXXXXXXXXXXXXXXX=


thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-0.6.1/src/seekstorm/add_result.rs:1847:15:
index out of bounds: the len is 5638 but the index is 18446744073702146056
stack backtrace:
   0:        0x10e7f425b - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf41a54e7ed5fe07
   1:        0x10e22099b - core::fmt::write::h526161fad96c5ad5
   2:        0x10e7c871e - std::io::Write::write_fmt::h4de0398536c8b0e4
   3:        0x10e7f859a - std::panicking::default_hook::{{closure}}::hffeef89117b5d267
   4:        0x10e7f80af - std::panicking::default_hook::h2f20b53f3264c5d5
   5:        0x10e7f9e21 - std::panicking::rust_panic_with_hook::h7919e8c602131afa
   6:        0x10e7f8f85 - std::panicking::begin_panic_handler::{{closure}}::h7bd628128f542977
   7:        0x10e7f8ee9 - std::sys::backtrace::__rust_end_short_backtrace::ha2fdb908654ed930
   8:        0x10e7f8ed3 - _rust_begin_unwind
   9:        0x10e8ca2d1 - core::panicking::panic_fmt::h292eaa4d42e451fa
  10:        0x10e8ca3b6 - core::panicking::panic_bounds_check::h1d1822a2cd031b6c
  11:        0x10e48acf6 - seekstorm::intersection::intersection_docid::{{closure}}::h7d84a1dff17a2fcd.4858
  12:        0x10e43b148 - seekstorm::intersection::intersection_blockid::{{closure}}::h439a6ccfcecdff2e.4855
  13:        0x10e432979 - <alloc::sync::Arc<tokio::sync::rwlock::RwLock<seekstorm::index::Index>> as seekstorm::search::Search>::search::{{closure}}::h08e48db7c8a2f510.4834
  14:        0x10e427c47 - seekstorm_server::api_endpoints::query_index_api::{{closure}}::h53d60e8d6a7c0511.4822
  15:        0x10e418dc4 - seekstorm_server::http_server::http_request_handler::{{closure}}::he141cfb8d0bf4d8f.4782
  16:        0x10e79d910 - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hab84192b8917d816
  17:        0x10e1d3133 - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::h6f113da6cc42bdf1
  18:        0x10e569643 - tokio::runtime::task::core::Core<T,S>::poll::h666dfe94ceba2153
  19:        0x10e1e0078 - tokio::runtime::task::raw::poll::h6be3611534d88a22
  20:        0x10e7fbe8d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h18a54404c6f874bd
  21:        0x10e802902 - tokio::runtime::task::raw::poll::hc78e731e5702ed1f
  22:        0x10e801164 - std::sys::backtrace::__rust_begin_short_backtrace::hb47b7926120e2886
  23:        0x10e800fa4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha71ab310b607c26d
  24:        0x10e7fb03b - std::sys::pal::unix::thread::Thread::new::thread_start::hcd19cc58b6db093a
  25:     0x7ff80450a18b - __pthread_start
zsh: abort      RUST_BACKTRACE=full ./seekstorm_server local_ip="0.0.0.0" local_port=8020`



Query 2: 1443 maple a

CURL for query 2: `curl --location 'http://127.0.0.1:8020/api/v1/index/0/query?query=1443%20maple%20a&offset=0&length=10' \
--header 'Content-Type: application/json' \
--header 'apikey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='`

Error for Query 2: `andy@Andys-iMac release % RUST_BACKTRACE=full ./seekstorm_server local_ip="0.0.0.0" local_port=8020
SeekStorm server v0.6.1 starting ...
Hit CTRL-C or enter 'quit' to shutdown server
opening index ...
index.bin name wikipedia id 0 version 3.2 3.2 level 1999 fields 2 2 facets 0 docs 130,987,896 deleted 0 segments 2048 time 0 s
Listening on: 0.0.0.0 8020 index dir /Users/andy/Downloads/SeekStorm-0.6.1/target/release/seekstorm_index master key XXXXXXXXXXXXXX=


thread 'tokio-runtime-worker' panicked at /Users/andy/Downloads/SeekStorm-0.6.1/src/seekstorm/intersection.rs:1683:37:
index out of bounds: the len is 704 but the index is 1023
stack backtrace:
   0:        0x102a5825b - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf41a54e7ed5fe07
   1:        0x10248499b - core::fmt::write::h526161fad96c5ad5
   2:        0x102a2c71e - std::io::Write::write_fmt::h4de0398536c8b0e4
   3:        0x102a5c59a - std::panicking::default_hook::{{closure}}::hffeef89117b5d267
   4:        0x102a5c0af - std::panicking::default_hook::h2f20b53f3264c5d5
   5:        0x102a5de21 - std::panicking::rust_panic_with_hook::h7919e8c602131afa
   6:        0x102a5cf85 - std::panicking::begin_panic_handler::{{closure}}::h7bd628128f542977
   7:        0x102a5cee9 - std::sys::backtrace::__rust_end_short_backtrace::ha2fdb908654ed930
   8:        0x102a5ced3 - _rust_begin_unwind
   9:        0x102b2e2d1 - core::panicking::panic_fmt::h292eaa4d42e451fa
  10:        0x102b2e3b6 - core::panicking::panic_bounds_check::h1d1822a2cd031b6c
  11:        0x1026ec4cb - seekstorm::intersection::intersection_docid::{{closure}}::h7d84a1dff17a2fcd.4858
  12:        0x10269f148 - seekstorm::intersection::intersection_blockid::{{closure}}::h439a6ccfcecdff2e.4855
  13:        0x102696979 - <alloc::sync::Arc<tokio::sync::rwlock::RwLock<seekstorm::index::Index>> as seekstorm::search::Search>::search::{{closure}}::h08e48db7c8a2f510.4834
  14:        0x10268bc47 - seekstorm_server::api_endpoints::query_index_api::{{closure}}::h53d60e8d6a7c0511.4822
  15:        0x10267cdc4 - seekstorm_server::http_server::http_request_handler::{{closure}}::he141cfb8d0bf4d8f.4782
  16:        0x102a01910 - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hab84192b8917d816
  17:        0x102437133 - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::h6f113da6cc42bdf1
  18:        0x1027cd643 - tokio::runtime::task::core::Core<T,S>::poll::h666dfe94ceba2153
  19:        0x102444078 - tokio::runtime::task::raw::poll::h6be3611534d88a22
  20:        0x102a5fe8d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h18a54404c6f874bd
  21:        0x102a66902 - tokio::runtime::task::raw::poll::hc78e731e5702ed1f
  22:        0x102a65164 - std::sys::backtrace::__rust_begin_short_backtrace::hb47b7926120e2886
  23:        0x102a64fa4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha71ab310b607c26d
  24:        0x102a5f03b - std::sys::pal::unix::thread::Thread::new::thread_start::hcd19cc58b6db093a
  25:     0x7ff80450a18b - __pthread_start
zsh: abort      RUST_BACKTRACE=full ./seekstorm_server local_ip="0.0.0.0" local_port=8020
`

What is interesting is if I add or remove characters from search query, there is no problems. Example "1443 maple av" and "1443 maple" queries work with no problem but "1443 maple a" crashes. Same with "123 main" and "123 main st chicago" works but crashes on "123 main st" .

**Comment by wolfgarbe** [comment]
Exceptions should be fixed with commit afd2e8f (all relevant changes are within intersection.rs). 

Please let me know if the fix works for you. Thanks.

**Comment by westadaptive** [comment]
Thank you very much! This has resolved the crashes. It works smoothly now. I really appreciate your help.

**Comment by wolfgarbe** [comment]
I appreciate your support in fixing the issue!
