### ISSUE TITLE
aarch64 build fails

### ISSUE THREAD

**Issue by Alexfilus** [SeekStorm/SeekStorm#6]
Hi! 
`cargo build --release` is failing on aarch64 because of src/seekstorm/intersection_simd.rs:438 intersection_vector16 
tag 0.7.0
macOS 15.0.1 (24A348)
M2 Max
cargo 1.82.0

**Comment by wolfgarbe** [comment]
Thank you very much for the report.

Building on aarch64 should be fixed with commit 86a0536 / v0.7.1 .

Please let me know if the fix works for you (I have no MacBook to verify). Thanks.

**Comment by Alexfilus** [comment]
There were several issues but I fixed them https://github.com/SeekStorm/SeekStorm/pull/7

**Comment by wolfgarbe** [comment]
Thank you!
